// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlwC5LExftIOzw5xxvcgd7-7UAiu6fOrg',
    appId: '1:448999733971:web:4dade3501769daf3853226',
    messagingSenderId: '448999733971',
    projectId: 'oneapp-229e5',
    authDomain: 'oneapp-229e5.firebaseapp.com',
    storageBucket: 'oneapp-229e5.firebasestorage.app',
    measurementId: 'G-7C1SSVY3KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3OOnPOgWwVhGehJXPcKN7ND3a8sXNh8w',
    appId: '1:448999733971:android:0abb64b092bb8fc4853226',
    messagingSenderId: '448999733971',
    projectId: 'oneapp-229e5',
    storageBucket: 'oneapp-229e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArus1vVhwhrvWOF5AVoKWPPU43rdKyKjI',
    appId: '1:448999733971:ios:75ebd03faaab3a11853226',
    messagingSenderId: '448999733971',
    projectId: 'oneapp-229e5',
    storageBucket: 'oneapp-229e5.firebasestorage.app',
    iosBundleId: 'com.example.appone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArus1vVhwhrvWOF5AVoKWPPU43rdKyKjI',
    appId: '1:448999733971:ios:75ebd03faaab3a11853226',
    messagingSenderId: '448999733971',
    projectId: 'oneapp-229e5',
    storageBucket: 'oneapp-229e5.firebasestorage.app',
    iosBundleId: 'com.example.appone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlwC5LExftIOzw5xxvcgd7-7UAiu6fOrg',
    appId: '1:448999733971:web:257166a6df16a723853226',
    messagingSenderId: '448999733971',
    projectId: 'oneapp-229e5',
    authDomain: 'oneapp-229e5.firebaseapp.com',
    storageBucket: 'oneapp-229e5.firebasestorage.app',
    measurementId: 'G-YGM5859N0V',
  );
}
